[package]
name = "yyx-bridge-android"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[dependencies]
cc = "1.0"
libc = "0.2"
nix = "0.13.0"

[features]
default = []
android = []