[package]
name = "bridge-arm"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.50"

[build-dependencies]
rand = "0.6.5"